### ISSUE TITLE
PLS link Illegible

### ISSUE THREAD

**Issue by geldons** [y20k/transistor#101]
Thought I could give VLC a break and run this Instead. Tried to listen to KCRW 89.9 FM using the only live link I can find, "http://legacy.kcrw.com/pls/kcrwsimulcast.pls", and it doesn't have a clue. Nice ap though, even one link that vlc can decode that this can't makes it redundant.

**Comment by y20k** [comment]
Hi @geldons ,

the problem with this particular station seems to be: The server that is hosting the pls-file, is probably not configured correctly. It should deliver the file with the correct mime type set.

There is a fix that would allow Transistor to be less strict (see #84), but the code is not complete/finished yet.

Anyway. I found a workaround, that worked - at least on my phone. Press the + button and add the actual stream URL: http://kcrw.streamguys1.com/kcrw_192k_mp3_on_air_internet_radio This URL can be found, when opening the pls in a text editor.

Hope that solves your problem.

Best regards.

**Comment by pelya** [comment]
Uh, about that patch, I'll update it, eventually. Maybe next week. Or the week after that.

One nice and easy workaround would be to simply display the faulty .pls or .m3u file in a TextView window to user, with the ability to select text and clickable links: http://stackoverflow.com/questions/2734270/how-do-i-make-links-in-a-textview-clickable

Probably need to check if the file is bigger than, say, 4 Kb, or contains binary stuff (any bytes below 0x20, except for \r \n and \t).

This would also solve the issue with multiple stations in a single .m3u file - Transistor uses only the last station URL from the file, and it's not always the best choice - half of radio websites I visit have some of their relays permanently down, and since most audio players will skip to the next working relay without complaining, .m3u never gets fixed.

So even if we parsed .m3u correctly, it would be nice to also show the .m3u file contents anyway, so user can click the best-working URL.

**Comment by morganchristiansson** [comment]
Having the same issue with this PLS file http://jungletrain.net/128kbps.pls

**Comment by y20k** [comment]
Yeah. Same here. The download of the pls takes some time. Also: once play has been tapped the stream takes very long until it starts playing back. Nice station music-wise though :-)

**Comment by gentoo-cba** [comment]
@y20k this is more common than you think. 

Shoutcast's own servers (old ones) that you can find at mp3.logosradionetwork.com/listen.pls or infowhores on stream server http://stream.infowars.com (stream1-3 too) run the windows shoutcast server do not properly give out the mime type. http:/streams.infowars.com is the newer shoutcast server that is running Linux for example which works fine.

If the mime type not defined maybe you should check if it's an MP3 stream by seeing if the decoder can read a second of data. I find this annoying because I can't listen to logos :)

**Comment by gentoo-cba** [comment]
@y20k is this fixed in the new release? If no mime time assume it's mp3 or have a test on the data to see if it is an mp3 stream.

**Comment by y20k** [comment]
> @y20k is this fixed in the new release?

@gentoo-cba the short version: the issue is still marked as open. :smile: 

The slightly longer one. Just skipping all mime type checks would probably result in a worse user experience. People would just try to enter the TLD of a radio station and there would be no response from the app. 

So the correct way to do this would be indeed to check the content of the requested URL. Transistor would need to check a) if it contains text (and then check if it is a playlist file) b) if it is an audio stream in one of the supported formats.
The problem: I am not sure on how to do that reliably. I would need to do some research and testing for that. And frankly I do not have the time right now. So sorry, the bug is still open: Meaning I might find the time to fix it in the future, or another contributor will fix it.

**Comment by y20k** [comment]
> Tried to listen to KCRW 89.9 FM using the only live link I can find, "http://legacy.kcrw.com/pls/kcrwsimulcast.pls"

The URL does not work anymore.
